### ISSUE TITLE
enable templates using html

### ISSUE THREAD

**Issue by barbalex** [STRd6/jadelet#13]
I may be outing myself as the basic newbie I am.

I love hamlet for:
- writing models using objects
- automatic binding between model code and DOM
- its general simplicity

So I expected an easy and quick start using it.

This is frustrated by two facts though:
1. the examples on http://hamlet.coffee/ are written in coffee script (idea: add a button to show them in plain javascript)
2. the templates have to be written in what looks like 'coffee for html'

While 'coffee for html' may be as great an idea as coffee itself for people immersed in it: most people work (and debug) with javascript and html.

Did I get something wrong? (I haven't worked with templates yet so maybe templates using html is generally a bad idea or simply not possible)

If not you could make it MUCH easier to take up hamlet by offering to write templates in html.

**Comment by jarinudom** [comment]
@barbalex There's also [Ractive.js](http://www.ractivejs.org), which uses handlebars-like syntax for its templates and can be used with Backbone models. It can be used with haml if you're on Rails, but it's not quite as simple as Hamlet (and the haml plugin is a little buggy, but it works well enough).
