### ISSUE TITLE
Change the name of this to avoid ambiguity

### ISSUE THREAD

**Issue by metaperl** [STRd6/jadelet#8]
[A quick google search](https://www.google.com/search?q=hamlet+templating&oq=hamlet+templating+&aqs=chrome..69i57j69i60j0l3j69i60.3526j0j1&sourceid=chrome&es_sm=91&ie=UTF-8) shows a number of web things named Hamlet.

What did you like about the name Hamlet? Could you possibly name it something a bit more representative of what it brings to the templating world?

**Comment by STRd6** [comment]
It's Jadelet now :1st_place_medal:
